spring:
  application:
    name: holiday-service
  datasource:
    url: jdbc:postgresql://postgres:5432/school_scheduler
    username: scheduler
    password: scheduler
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  cloud:
    config:
      uri: http://config-service:8888
      fail-fast: true
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
