spring:
  application:
    name: config-service
  datasource:
    url: jdbc:postgresql://postgres:5432/school_scheduler
    username: scheduler
    password: scheduler
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
